<template>
    <v-sheet>
        <v-text-field
            v-model="caseStore.caseContent.姓名"
            class="my-4"
            label="姓名"
            variant="outlined"
            hide-details="auto"
        />
        <v-text-field
            v-model="caseStore.caseContent.性别"
            class="my-4"
            label="性别"
            variant="outlined"
            hide-details="auto"
        />
        <v-text-field
            v-model="caseStore.caseContent.年龄"
            class="my-4"
            label="年龄"
            variant="outlined"
            hide-details="auto"
        />
        <v-text-field
            v-model="caseStore.caseContent.主诉"
            label="主诉"
            variant="outlined"
            hide-details="auto"
        />
        <v-textarea
            v-model="caseStore.caseContent.现病史"
            class="my-4"
            rows="1"
            auto-grow
            label="现病史"
            variant="outlined"
            hide-details="auto"
        />
        <v-textarea
            v-model="caseStore.caseContent.既往史"
            class="my-4"
            rows="1"
            auto-grow
            label="既往史"
            variant="outlined"
            hide-details="auto"
        />
        <v-textarea
            v-model="caseStore.caseContent.查体"
            class="my-4"
            rows="1"
            auto-grow
            label="查体："
            variant="outlined"
            hide-details="auto"
        />
        <v-textarea
            v-model="caseStore.caseContent.专科查体"
            rows="1"
            class="my-4"
            auto-grow
            label="专科查体："
            variant="outlined"
            hide-details="auto"
        />
        <v-textarea
            v-model="caseStore.caseContent.辅助检查"
            rows="1"
            class="my-4"
            auto-grow
            label="辅助检查："
            variant="outlined"
            hide-details="auto"
        />
        <v-textarea
            v-model="caseStore.caseContent.诊断"
            class="my-4"
            rows="1"
            auto-grow
            label="诊断："
            variant="outlined"
            hide-details="auto"
        />
        <v-textarea
            v-model="caseStore.caseContent.治疗"
            class="my-4"
            rows="1"
            auto-grow
            label="治疗："
            variant="outlined"
            hide-details="auto"
        />
        <v-textarea
            v-model="caseStore.caseContent.手术"
            class="my-4"
            rows="1"
            auto-grow
            label="手术："
            variant="outlined"
            hide-details="auto"
        />
        <v-textarea
            v-model="caseStore.caseContent.病理"
            class="my-4"
            rows="1"
            auto-grow
            label="病理："
            variant="outlined"
            hide-details="auto"
        />
    </v-sheet>
</template>

<script setup>
const caseStore = useCaseStore()
</script>
