<template>
    <!-- <v-sheet class="overflow-auto">
        <v-list>
            <v-list-item v-for="(value, key, index) in simCaseJson" :key="index">
                <span class="font-weight-bold">{{ key }}：</span>{{ value }}
            </v-list-item>
        </v-list>
    </v-sheet> -->
    <v-form>
        <v-sheet class="ma-2 pa-2">
            <v-text-field
                v-model="simCaseJson.姓名"
                class="my-4"
                label="姓名"
                :variant="varTextField"
                hide-details="auto"
            />
            <v-text-field
                v-model="simCaseJson.性别"
                class="my-4"
                label="性别"
                :variant="varTextField"
                hide-details="auto"
            />
            <v-text-field
                v-model="simCaseJson.年龄"
                class="my-4"
                label="年龄"
                :variant="varTextField"
                hide-details="auto"
            />
            <v-text-field
                v-model="simCaseJson.主诉"
                label="主诉"
                :variant="varTextField"
                hide-details="auto"
            />
            <v-textarea
                v-model="simCaseJson.现病史"
                class="my-4"
                rows="1"
                auto-grow
                label="现病史"
                :variant="varTextField"
                hide-details="auto"
            />
            <v-textarea
                v-model="simCaseJson.既往史"
                class="my-4"
                rows="1"
                auto-grow
                label="既往史"
                :variant="varTextField"
                hide-details="auto"
            />
            <v-textarea
                v-model="simCaseJson.查体"
                class="my-4"
                rows="1"
                auto-grow
                label="查体："
                :variant="varTextField"
                hide-details="auto"
            />
            <v-textarea
                v-model="simCaseJson.专科查体"
                rows="1"
                class="my-4"
                auto-grow
                label="专科查体："
                :variant="varTextField"
                hide-details="auto"
            />
            <v-textarea
                v-model="simCaseJson.辅助检查"
                rows="1"
                class="my-4"
                auto-grow
                label="辅助检查："
                :variant="varTextField"
                hide-details="auto"
            />
            <v-textarea
                v-model="simCaseJson.诊断"
                class="my-4"
                rows="1"
                auto-grow
                label="诊断："
                :variant="varTextField"
                hide-details="auto"
            />
            <v-textarea
                v-model="simCaseJson.治疗"
                class="my-4"
                rows="1"
                auto-grow
                label="治疗："
                :variant="varTextField"
                hide-details="auto"
            />
            <v-textarea
                v-model="simCaseJson.手术"
                class="my-4"
                rows="1"
                auto-grow
                label="手术："
                :variant="varTextField"
                hide-details="auto"
            />
            <v-textarea
                v-model="simCaseJson.病理"
                class="my-4"
                rows="1"
                auto-grow
                label="病理："
                :variant="varTextField"
                hide-details="auto"
            />
        </v-sheet>
    </v-form>
</template>

<script setup>
const caseStore = useCaseStore()
const { simCaseJson } = storeToRefs(caseStore)

const varTextField = ref('outlined')
</script>
