<template>
  <v-sheet class="text-body-1 pa-5 overflow-auto mx-4" elevation="4" rounded="lg" height="55vh">
    <v-text-field
      v-model="recordStore.record.case.姓名"
      class="mt-0 mb-4"
      label="姓名"
      variant="outlined"
      hide-details="auto"
    />
    <v-text-field
      v-model="recordStore.record.case.性别"
      class="my-4"
      label="性别"
      variant="outlined"
      hide-details="auto"
    />
    <v-text-field
      v-model="recordStore.record.case.年龄"
      class="my-4"
      label="年龄"
      variant="outlined"
      hide-details="auto"
    />
    <v-text-field
      v-model="recordStore.record.case.主诉"
      label="主诉"
      variant="outlined"
      hide-details="auto"
    />
    <v-textarea
      v-model="recordStore.record.case.现病史"
      class="my-4"
      rows="1"
      auto-grow
      label="现病史"
      variant="outlined"
      hide-details="auto"
    />
    <v-textarea
      v-model="recordStore.record.case.既往史"
      class="my-4"
      rows="1"
      auto-grow
      label="既往史"
      variant="outlined"
      hide-details="auto"
    />
    <v-textarea
      v-model="recordStore.record.case.查体"
      class="my-4"
      rows="1"
      auto-grow
      label="查体："
      variant="outlined"
      hide-details="auto"
    />
    <v-textarea
      v-model="recordStore.record.case.专科查体"
      rows="1"
      class="my-4"
      auto-grow
      label="专科查体："
      variant="outlined"
      hide-details="auto"
    />
    <v-textarea
      v-model="recordStore.record.case.辅助检查"
      rows="1"
      class="my-4"
      auto-grow
      label="辅助检查："
      variant="outlined"
      hide-details="auto"
    />
    <v-textarea
      v-model="recordStore.record.case.诊断"
      class="my-4"
      rows="1"
      auto-grow
      label="诊断："
      variant="outlined"
      hide-details="auto"
    />
    <v-textarea
      v-model="recordStore.record.case.治疗"
      class="my-4"
      rows="1"
      auto-grow
      label="治疗："
      variant="outlined"
      hide-details="auto"
    />
    <v-textarea
      v-model="recordStore.record.case.手术"
      class="my-4"
      rows="1"
      auto-grow
      label="手术："
      variant="outlined"
      hide-details="auto"
    />
    <v-textarea
      v-model="recordStore.record.case.病理"
      class="mb-0"
      rows="1"
      auto-grow
      label="病理："
      variant="outlined"
      hide-details="auto"
    />
  </v-sheet>
</template>

<script setup>
const recordStore = useRecordStore()
</script>
